"""auto-20260208-172258

Revision ID: 24305fda27dc
Revises: c81fb44d6b3f
Create Date: 2026-02-08 09:23:01.562834
"""




revision = '24305fda27dc'
down_revision = 'c81fb44d6b3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
