"""auto-20260208-172113

Revision ID: 2ba71b2e6859
Revises: 7f4b2a1d9d1a
Create Date: 2026-02-08 09:21:20.251500
"""
from alembic import op
import sqlalchemy as sa



revision = '2ba71b2e6859'
down_revision = '7f4b2a1d9d1a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
