"""auto-20260208-172357

Revision ID: 5dc950a4dcb3
Revises: 24305fda27dc
Create Date: 2026-02-08 09:24:00.750717
"""




revision = '5dc950a4dcb3'
down_revision = '24305fda27dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
