"""auto-20260208-224941

Revision ID: 63170a13c83b
Revises: 84ebe8eaf884
Create Date: 2026-02-08 14:49:49.383129
"""




revision = '63170a13c83b'
down_revision = '84ebe8eaf884'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
