"""auto-20260208-225438

Revision ID: 683ad94592b8
Revises: 63170a13c83b
Create Date: 2026-02-08 14:54:41.475679
"""
from alembic import op
import sqlalchemy as sa



revision = '683ad94592b8'
down_revision = '63170a13c83b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
