"""auto-20260208-173932

Revision ID: 69708d04002e
Revises: c3aec3bab7fd
Create Date: 2026-02-08 09:39:35.895303
"""




revision = '69708d04002e'
down_revision = 'c3aec3bab7fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
