"""auto-20260208-174109

Revision ID: 84ebe8eaf884
Revises: 69708d04002e
Create Date: 2026-02-08 09:41:12.639664
"""




revision = '84ebe8eaf884'
down_revision = '69708d04002e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
