"""auto-20260208-172946

Revision ID: a2d4dc537188
Revises: ec150bba70e5
Create Date: 2026-02-08 09:29:49.913747
"""




revision = 'a2d4dc537188'
down_revision = 'ec150bba70e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
