"""auto-20260208-173108

Revision ID: aed6b983d870
Revises: a2d4dc537188
Create Date: 2026-02-08 09:31:15.952187
"""




revision = 'aed6b983d870'
down_revision = 'a2d4dc537188'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
