"""auto-20260208-173753

Revision ID: c3aec3bab7fd
Revises: aed6b983d870
Create Date: 2026-02-08 09:38:01.299800
"""
from alembic import op
import sqlalchemy as sa



revision = 'c3aec3bab7fd'
down_revision = 'aed6b983d870'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
