"""auto-20260208-172213

Revision ID: c81fb44d6b3f
Revises: 2ba71b2e6859
Create Date: 2026-02-08 09:22:17.531377
"""
from alembic import op
import sqlalchemy as sa



revision = 'c81fb44d6b3f'
down_revision = '2ba71b2e6859'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
