"""auto-20260208-172819

Revision ID: ec150bba70e5
Revises: 5dc950a4dcb3
Create Date: 2026-02-08 09:28:22.454559
"""
from alembic import op
import sqlalchemy as sa



revision = 'ec150bba70e5'
down_revision = '5dc950a4dcb3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
