name: Full CI

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

jobs:
  full_ci:
    name: Common CI
    uses: ./.github/workflows/Common-CI.yml
    with:
      upload_client_artifact: true
