name: PR CI (Deep)

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main]

jobs:
  run_common:
    name: Common CI
    uses: ./.github/workflows/ci-common.yml
    with:
      upload_client_artifact: true
