name: Quiet CI

on:
  push:
    branches-ignore:
      - main
      - develop

jobs:
  quiet_ci:
    name: Common CI
    uses: ./.github/workflows/Common-CI.yml
    with:
      upload_client_artifact: false
